function FEM_2d(mshfile, boundaryfile, ppmshfile)

[Surf Line] = LoadBoundaryFile(boundaryfile);

Material = Surf';

% copper resistivity 
ro_Cu = 1.7e-8;

tic;
% read the mesh file generated by Gmesh
[MeshFormat NodeCor EleList] = LoadMeshFile(mshfile);

tRF = toc;
fprintf('Time for reading the File: %.2f s!\n',tRF);



%Triangular list
LineEle = EleList.LineEle;
TriEle = EleList.TriEle;

% read the nodes for all the triangles at surface
LineNode = LineEle(:,[4 6:7]);
TriEleNode = TriEle(:,[4 6:8]);  


% NodeCor is the node coornidates, we adjust the node coornidate to micro
% unit (10^-6 unit). Node_Num is the number of nodes.
Node_Num = size(NodeCor,1);
NodeCor = NodeCor*10^-6;

tic;
KBDB_2d = BDB_2d(Node_Num, TriEle, NodeCor, Material);
tSF = toc;
fprintf('Time for building finite element matrix K: %.2f s!\n',tSF);

tic;
K = KBDB_2d;
f = sparse(Node_Num,1);

[a, b_num] = size(Line);

for i = 1:b_num
    [K f] = boundary_2d(LineEle, K, f, Line(1,i), Line(2,i));
end

Volt = K\f;

TimeStep = 0;
PostFileO(Node_Num,mshfile,TimeStep,Volt,ppmshfile);
